### PR TITLE
 Several Possible Bugs

### PR DESCRIPTION
**Pull request by steamraven**
While working on another feature, I came across several possible small bugs.  They are all small enough, I didn't think they warranted a pull request each.

As this is my first pull request for this project, please let me know how you would like this formatted.  I am very willing to adjust, reword, or split this out.

### CODE REVIEW

**Comment by steamraven** [comment]
Ran through black

**Comment by brickbots** [comment]
Hi @steamraven !  Thanks so much for spotting and working to fix these issues, nice work 🎉 

The catalog system is currently under active refactoring in #63, so some of the issues in setup.py and ui/catalog may already be fixed, or might not exist in the new code.  So I think we can leave them to the side for now.

Since the remainder are all small and self-contained, I can just apply them in main if that's okay with you.  If you'd like to get credit for the fixes/PR (as you deserve!) then would it be possible to pull out the setup and ui/catalog commits?

I see Black is still complaining even after you run your code through it.  Let me know if you want some help with this.  Black can sometimes change specific formatting between major versions, so I'd verify you are using the one our CI relies on:
`black[colorama]==23.7.0`

Thank you again!!!

**Comment by steamraven** [comment]
I'll try the black again (and I will add it to requirements_dev.txt) .
As for the setup.py and ui/catalog.py, I can yank it so that it can merge.

However, I checked, and the ui/catalog.py errors are still in #63 . I can put a separate pull for that

**Comment by brickbots** [comment]
Thank you for reworking the PR and, yeah, the bugs may end up there after @mrosseel is done, but we can wait until his PR is ready before getting them patched up.  

Thanks for adding black to the requirements_dev as well :+1:

**Comment by brickbots** [comment]
This looks ready to merge to me, @steamraven 🎉   Do you think it's ready to remove the [WIP] and be merged?

**Pull request merged**
