### PR TITLE
Flat Mount 

### PR DESCRIPTION
**Pull request by cosmoteer**
Tasks completed:
 Add flat mount option in Options Menu
 Flip IMU axis
 Invert azimuth difference from negative to positive in locate module
 Flip alt_offset to be that of left hand mount in integrator module

### CODE REVIEW

**Comment by mrosseel** [comment]
@cosmoteer you need to format your python files with the black file formatter, there's an automatic test on PR's to make sure everyone follows the rules :). See my pre commit hook below.

For the rest this seems fine to me, although I don't really understand the terminology 'flat' - it would be nice to document this with a picture in the docs. Not faulting you, I haven't changed any docs either 😢 

```
> cat .pre-commit-config.yaml 
  # See https://pre-commit.com for more information
    # See https://pre-commit.com/hooks.html for more hooks
    repos:
      - repo: https://github.com/ambv/black
        rev: 23.3.0
        hooks:
          - id: black
            language_version: python3.9
```

**Comment by cosmoteer** [comment]
> @cosmoteer you need to format your python files with the black file formatter, there's an automatic test on PR's to make sure everyone follows the rules :). See my pre commit hook below.
> 
> For the rest this seems fine to me, although I don't really understand the terminology 'flat' - it would be nice to document this with a picture in the docs. Not faulting you, I haven't changed any docs either 😢
> 
> ```
> > cat .pre-commit-config.yaml 
>   # See https://pre-commit.com for more information
>     # See https://pre-commit.com/hooks.html for more hooks
>     repos:
>       - repo: https://github.com/ambv/black
>         rev: 23.3.0
>         hooks:
>           - id: black
>             language_version: python3.9
> ```

Got it. I’ll format and add a pic/update docs later tonight.

**Comment by cosmoteer** [comment]
@mrosseel @brickbots Linted, updated doc, added pictures. Could pipeline be re-run?

**Comment by brickbots** [comment]
Thanks @cosmoteer !  I'm going to merge this and do a patch release (1.6.1) to add support for Flat mode.  Thank you for also updating the docs 🎉

**Pull request merged**
