### PR TITLE
Reformat RA status to Hours and Minutes

### PR DESCRIPTION
**Pull request by cosmoteer**

### CODE REVIEW

**Comment by mrosseel** [comment]
looks good, maybe it would be a good idea to move this to a utility method so we can reuse this in the future?
Something like

```
def ra_to_hms(ra:float) -> str:
   ...

```
in calc_utils.py ?

**Comment by cosmoteer** [comment]
That’s a good idea. I’ll make the change.

**Comment by cosmoteer** [comment]
@brickbots apologies for the delay, I've been busy preparing for a move. Util func created.

**Comment by mrosseel** [comment]
hi, looks good, would still prefer typing hints, mostly as documentation for the user.

def ra_to_hms(ra):
==>
def ra_to_hms(ra: float) -> Tuple[float, float, float]:

**Comment by mrosseel** [comment]
@cosmoteer do you want me to fix this for you? Would like to get this merged, thx!

**Comment by cosmoteer** [comment]
@brickbots sorry for the delay, but please go ahead. If I make any commits I’d want to test it and I don’t have time to get out under the stars for a while.

**Comment by mrosseel** [comment]
replaced by #93

**Pull request closed without merging**
